import 'package:flutter/material.dart';

class Product {
  final String image, title, description;
  final int price, size, id;
  final Color color;
  Product({
    required this.id,
    required this.image,
    required this.title,
    required this.price,
    required this.description,
    required this.size,
    required this.color,
  });
}

List<Product> Products = [
  Product(
      id: 1,
      title: "Ruby Tutorial",
      price: 999,
      size: 12,
      description: dummyText,
      image: "images/book10.png",
      color: Colors.black),
  Product(
      id: 2,
      title: "C# Language",
      price: 999,
      size: 8,
      description: dummyText,
      image: "images/book9.png",
      color: Colors.black),
  Product(
      id: 3,
      title: "C# Programming",
      price: 999,
      size: 10,
      description: dummyText,
      image: "images/book7.png",
      color: Colors.black),
  Product(
      id: 4,
      title: "Flutter Advance",
      price: 999,
      size: 11,
      description: dummyText,
      image: "images/book6.png",
      color: Colors.black),
  Product(
      id: 5,
      title: "Data Structure",
      price: 999,
      size: 12,
      description: dummyText,
      image: "images/book8.png",
      color: Colors.black),
  Product(
    id: 6,
    title: "Ruby Tutorial",
    price: 999,
    size: 12,
    description: dummyText,
    image: "images/book10.png",
    color: Colors.black,
  ),
  Product(
    id: 7,
    title: "The C book",
    price: 799,
    size: 12,
    description: dummyText,
    image: "images/book0.png",
    color: Colors.black,
  ),
  Product(
    id: 8,
    title: "Flutter Advance",
    price: 899,
    size: 12,
    description: dummyText,
    image: "images/book6.png",
    color: Colors.black,
  ),
  Product(
    id: 9,
    title: "C# Language",
    price: 699,
    size: 12,
    description: dummyText,
    image: "images/book9.png",
    color: Colors.black,
  ),Product(
    id: 10,
    title: "The C book",
    price: 799,
    size: 12,
    description: dummyText,
    image: "images/book0.png",
    color: Colors.black,
  ),
  Product(
      id: 11,
      title: "Data Structure",
      price: 599,
      size: 12,
      description: dummyText,
      image: "images/book8.png",
      color: Colors.black),
  Product(
      id: 12,
      title: "C# Language",
      price: 699,
      size: 8,
      description: dummyText,
      image: "images/book9.png",
      color: Colors.black),
  Product(
      id: 13,
      title: "C# Programming",
      price: 699,
      size: 10,
      description: dummyText,
      image: "images/book7.png",
      color: Colors.black),
  Product(
      id: 14,
      title: "Flutter Advance",
      price: 899,
      size: 11,
      description: dummyText,
      image: "images/book6.png",
      color: Colors.black),
  Product(
      id: 15,
      title: "Data Structure",
      price: 599,
      size: 12,
      description: dummyText,
      image: "images/book8.png",
      color: Colors.black),
  Product(
    id: 16,
    title: "Ruby Tutorial",
    price: 999,
    size: 12,
    description: dummyText,
    image: "images/book10.png",
    color: Colors.black,
  ),
  Product(
    id: 17,
    title: "The C book",
    price: 799,
    size: 12,
    description: dummyText,
    image: "images/book0.png",
    color: Colors.black,
  ),
  Product(
    id: 18,
    title: "Flutter Advance",
    price: 899,
    size: 12,
    description: dummyText,
    image: "images/book6.png",
    color: Colors.black,
  ),
  Product(
    id: 6,
    title: "C# Language",
    price: 699,
    size: 12,
    description: dummyText,
    image: "images/book9.png",
    color: Colors.black,
  ),Product(
    id: 6,
    title: "The C book",
    price: 799,
    size: 12,
    description: dummyText,
    image: "images/book0.png",
    color: Colors.black,
  ),
  Product(
    id: 6,
    title: "The C book",
    price: 799,
    size: 12,
    description: dummyText,
    image: "images/book5.png",
    color: Colors.black,
  ),
  Product(
    id: 6,
    title: "Ruby Tutorial",
    price: 999,
    size: 12,
    description: dummyText,
    image: "images/book10.png",
    color: Colors.black,
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
